# ==============================================================================
# FLAG SERVICE - EXTERNAL SECRETS
# ==============================================================================
# Descrição: Integração com AWS Secrets Manager para credenciais do RDS
# ==============================================================================

# ------------------------------------------------------------------------------
# Secret - Credenciais AWS (para o External Secrets Operator)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster-flag
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/component: flag
    app.kubernetes.io/part-of: togglemaster
type: Opaque
data:
  access-key: COLE_SUA_ACCESS_KEY_AQUI_EM_BASE64
  secret-access-key: COLE_SUA_SECRET_ACCESS_KEY_AQUI_EM_BASE64
  session-token: COLE_SEU_SESSION_TOKEN_AQUI_EM_BASE64
---
# ------------------------------------------------------------------------------
# SecretStore - Conexão com AWS Secrets Manager
# ------------------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-us-east-1
  namespace: togglemaster-flag
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/component: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-credentials
            key: session-token

---
# ------------------------------------------------------------------------------
# ExternalSecret - Credenciais do RDS
# ------------------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-service-rds
  namespace: togglemaster-flag
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/component: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: flag-service-rds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-fcddecfa-1707-4a33-be4d-cb6124ef86ae
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-fcddecfa-1707-4a33-be4d-cb6124ef86ae
        property: password
