# ==============================================================================
# EVALUATION SERVICE - AWS CREDENTIALS
# ==============================================================================
# Descrição: Credenciais AWS para acesso ao SQS e outros serviços
# ==============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster-evaluation
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/component: evaluation
    app.kubernetes.io/part-of: togglemaster
type: Opaque
data:
  access-key: COLE_SUA_ACCESS_KEY_AQUI_EM_BASE64
  secret-access-key: COLE_SUA_SECRET_ACCESS_KEY_AQUI_EM_BASE64
  session-token: COLE_SEU_SESSION_TOKEN_AQUI_EM_BASE64