apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster-analytics
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: togglemaster
type: Opaque
data:
  access-key: COLE_SUA_ACCESS_KEY_AQUI_EM_BASE64
  secret-access-key: COLE_SUA_SECRET_ACCESS_KEY_AQUI_EM_BASE64
  session-token: COLE_SEU_SESSION_TOKEN_AQUI_EM_BASE64